name: Test Diff Previous Tag

on:
  push:
    tags:
      - release/v*

  workflow_dispatch:
    inputs:
      version:
        description: "릴리즈 버전 (예: 1.2.3)"
        required: true
        type: string
      force_full_deploy:
        description: "전체 배포 강제 실행 (detect-changes 무시)"
        required: false
        default: false
        type: boolean

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag and changed files
        id: set
        run: |
          CURRENT_TAG="${GITHUB_REF_NAME#refs/tags/}"
          PREV_TAG=$(git tag --sort=-creatordate \
          | grep '^release/v' \
          | grep -v "^$CURRENT_TAG\$" \
          | while read TAG; do
              if [ "$(git log --format=%ct -1 "$TAG")" -lt "$(git log --format=%ct -1 "$CURRENT_TAG")" ]; then
                echo "$TAG"
                break
              fi
            done)

          echo "Current tag: $CURRENT_TAG"
          echo "Previous tag: $PREV_TAG"

          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, forcing full deploy."
            echo 'deploy=["all"]' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          FILES=$(git diff --name-only "$PREV_TAG" "$CURRENT_TAG")

          if [ -z "$FILES" ]; then
            echo "No files changed between $PREV_TAG and $CURRENT_TAG"
            echo 'deploy=[]' >> "$GITHUB_OUTPUT"
          else
            echo "Changed files:"
            echo "$FILES"
            echo 'deploy=["some"]' >> "$GITHUB_OUTPUT"
          fi
